# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QSpinBox, QTabWidget,
    QTableWidget, QTableWidgetItem, QTextBrowser, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(440, 605)
        MainWindow.setMinimumSize(QSize(440, 605))
        MainWindow.setMaximumSize(QSize(440, 605))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.cmb_buadRate = QComboBox(self.centralwidget)
        self.cmb_buadRate.setObjectName(u"cmb_buadRate")
        self.cmb_buadRate.setGeometry(QRect(130, 30, 101, 24))
        self.cmb_Port = QComboBox(self.centralwidget)
        self.cmb_Port.setObjectName(u"cmb_Port")
        self.cmb_Port.setGeometry(QRect(240, 30, 101, 24))
        self.lbl_deviceName = QLabel(self.centralwidget)
        self.lbl_deviceName.setObjectName(u"lbl_deviceName")
        self.lbl_deviceName.setGeometry(QRect(10, 10, 101, 16))
        self.lbl_baudRate = QLabel(self.centralwidget)
        self.lbl_baudRate.setObjectName(u"lbl_baudRate")
        self.lbl_baudRate.setGeometry(QRect(130, 10, 101, 16))
        self.lbl_Port = QLabel(self.centralwidget)
        self.lbl_Port.setObjectName(u"lbl_Port")
        self.lbl_Port.setGeometry(QRect(240, 10, 101, 16))
        self.txt_deviceNameEntry = QLineEdit(self.centralwidget)
        self.txt_deviceNameEntry.setObjectName(u"txt_deviceNameEntry")
        self.txt_deviceNameEntry.setGeometry(QRect(10, 30, 113, 24))
        self.btn_addDevice = QPushButton(self.centralwidget)
        self.btn_addDevice.setObjectName(u"btn_addDevice")
        self.btn_addDevice.setGeometry(QRect(350, 30, 82, 24))
        self.tbl_deviceTable = QTableWidget(self.centralwidget)
        if (self.tbl_deviceTable.columnCount() < 3):
            self.tbl_deviceTable.setColumnCount(3)
        self.tbl_deviceTable.setObjectName(u"tbl_deviceTable")
        self.tbl_deviceTable.setGeometry(QRect(10, 60, 422, 141))
        self.tbl_deviceTable.setFrameShape(QFrame.StyledPanel)
        self.tbl_deviceTable.setColumnCount(3)
        self.tbl_deviceTable.horizontalHeader().setVisible(False)
        self.tbl_deviceTable.horizontalHeader().setDefaultSectionSize(140)
        self.tbl_deviceTable.verticalHeader().setVisible(True)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 240, 421, 16))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.tab_gameSelection = QTabWidget(self.centralwidget)
        self.tab_gameSelection.setObjectName(u"tab_gameSelection")
        self.tab_gameSelection.setGeometry(QRect(10, 260, 421, 331))
        self.tab_RSE = QWidget()
        self.tab_RSE.setObjectName(u"tab_RSE")
        self.cmb_rse_category = QComboBox(self.tab_RSE)
        self.cmb_rse_category.setObjectName(u"cmb_rse_category")
        self.cmb_rse_category.setGeometry(QRect(140, 30, 121, 24))
        self.cmb_rse_encounter = QComboBox(self.tab_RSE)
        self.cmb_rse_encounter.setObjectName(u"cmb_rse_encounter")
        self.cmb_rse_encounter.setGeometry(QRect(280, 30, 121, 24))
        self.lbl_rseCategory = QLabel(self.tab_RSE)
        self.lbl_rseCategory.setObjectName(u"lbl_rseCategory")
        self.lbl_rseCategory.setGeometry(QRect(140, 10, 61, 16))
        self.lbl_rse_enctounter = QLabel(self.tab_RSE)
        self.lbl_rse_enctounter.setObjectName(u"lbl_rse_enctounter")
        self.lbl_rse_enctounter.setGeometry(QRect(280, 10, 61, 16))
        self.btn_rse_startSequence = QPushButton(self.tab_RSE)
        self.btn_rse_startSequence.setObjectName(u"btn_rse_startSequence")
        self.btn_rse_startSequence.setGeometry(QRect(300, 270, 101, 24))
        self.chk_rse_BattleRecord = QCheckBox(self.tab_RSE)
        self.chk_rse_BattleRecord.setObjectName(u"chk_rse_BattleRecord")
        self.chk_rse_BattleRecord.setGeometry(QRect(10, 150, 111, 22))
        self.chk_rse_painting = QCheckBox(self.tab_RSE)
        self.chk_rse_painting.setObjectName(u"chk_rse_painting")
        self.chk_rse_painting.setGeometry(QRect(10, 170, 111, 22))
        self.chk_rse_liveBattery = QCheckBox(self.tab_RSE)
        self.chk_rse_liveBattery.setObjectName(u"chk_rse_liveBattery")
        self.chk_rse_liveBattery.setGeometry(QRect(10, 190, 111, 22))
        self.spb_rse_targetAdvance = QSpinBox(self.tab_RSE)
        self.spb_rse_targetAdvance.setObjectName(u"spb_rse_targetAdvance")
        self.spb_rse_targetAdvance.setGeometry(QRect(10, 60, 121, 25))
        self.spb_rse_targetAdvance.setMaximum(10000000)
        self.lbl_rse_targetMS = QLabel(self.tab_RSE)
        self.lbl_rse_targetMS.setObjectName(u"lbl_rse_targetMS")
        self.lbl_rse_targetMS.setGeometry(QRect(10, 40, 81, 16))
        self.lbl_rse_paintingTimer = QLabel(self.tab_RSE)
        self.lbl_rse_paintingTimer.setObjectName(u"lbl_rse_paintingTimer")
        self.lbl_rse_paintingTimer.setGeometry(QRect(10, 90, 101, 16))
        self.spb_rse_paintingTime = QSpinBox(self.tab_RSE)
        self.spb_rse_paintingTime.setObjectName(u"spb_rse_paintingTime")
        self.spb_rse_paintingTime.setEnabled(False)
        self.spb_rse_paintingTime.setGeometry(QRect(10, 110, 121, 25))
        self.spb_rse_paintingTime.setMaximum(10000000)
        self.txb_rse_preReqs = QTextBrowser(self.tab_RSE)
        self.txb_rse_preReqs.setObjectName(u"txb_rse_preReqs")
        self.txb_rse_preReqs.setGeometry(QRect(140, 60, 261, 201))
        self.txb_rse_preReqs.setFrameShape(QFrame.Box)
        self.txb_rse_preReqs.setFrameShadow(QFrame.Plain)
        self.cmb_rse_deviceSel = QComboBox(self.tab_RSE)
        self.cmb_rse_deviceSel.setObjectName(u"cmb_rse_deviceSel")
        self.cmb_rse_deviceSel.setGeometry(QRect(180, 270, 51, 24))
        self.lbl_rse_deviceSel = QLabel(self.tab_RSE)
        self.lbl_rse_deviceSel.setObjectName(u"lbl_rse_deviceSel")
        self.lbl_rse_deviceSel.setGeometry(QRect(140, 270, 51, 16))
        self.tab_gameSelection.addTab(self.tab_RSE, "")
        self.tab_FRLG = QWidget()
        self.tab_FRLG.setObjectName(u"tab_FRLG")
        self.cmb_frlg_category = QComboBox(self.tab_FRLG)
        self.cmb_frlg_category.setObjectName(u"cmb_frlg_category")
        self.cmb_frlg_category.setGeometry(QRect(140, 30, 121, 24))
        self.lbl_frlg_emcounterSel = QLabel(self.tab_FRLG)
        self.lbl_frlg_emcounterSel.setObjectName(u"lbl_frlg_emcounterSel")
        self.lbl_frlg_emcounterSel.setGeometry(QRect(280, 10, 61, 16))
        self.cmb_frlg_enctounterSel = QComboBox(self.tab_FRLG)
        self.cmb_frlg_enctounterSel.setObjectName(u"cmb_frlg_enctounterSel")
        self.cmb_frlg_enctounterSel.setGeometry(QRect(280, 30, 121, 24))
        self.lbl_frlg_category = QLabel(self.tab_FRLG)
        self.lbl_frlg_category.setObjectName(u"lbl_frlg_category")
        self.lbl_frlg_category.setGeometry(QRect(140, 10, 61, 16))
        self.cmb_frlg_buttonSel = QComboBox(self.tab_FRLG)
        self.cmb_frlg_buttonSel.setObjectName(u"cmb_frlg_buttonSel")
        self.cmb_frlg_buttonSel.setGeometry(QRect(10, 210, 71, 24))
        self.lbl_frlg_button = QLabel(self.tab_FRLG)
        self.lbl_frlg_button.setObjectName(u"lbl_frlg_button")
        self.lbl_frlg_button.setGeometry(QRect(10, 190, 61, 16))
        self.spb_frlg_introTimer = QSpinBox(self.tab_FRLG)
        self.spb_frlg_introTimer.setObjectName(u"spb_frlg_introTimer")
        self.spb_frlg_introTimer.setGeometry(QRect(10, 60, 121, 25))
        self.spb_frlg_introTimer.setMaximum(10000000)
        self.lbl_frlg_introTimer = QLabel(self.tab_FRLG)
        self.lbl_frlg_introTimer.setObjectName(u"lbl_frlg_introTimer")
        self.lbl_frlg_introTimer.setGeometry(QRect(10, 40, 111, 16))
        self.lbl_frlg_totalTime = QLabel(self.tab_FRLG)
        self.lbl_frlg_totalTime.setObjectName(u"lbl_frlg_totalTime")
        self.lbl_frlg_totalTime.setGeometry(QRect(10, 140, 111, 16))
        self.spb_frlg_totalTime = QSpinBox(self.tab_FRLG)
        self.spb_frlg_totalTime.setObjectName(u"spb_frlg_totalTime")
        self.spb_frlg_totalTime.setGeometry(QRect(10, 160, 121, 25))
        self.spb_frlg_totalTime.setMaximum(10000000)
        self.spb_frlg_tvFrames = QSpinBox(self.tab_FRLG)
        self.spb_frlg_tvFrames.setObjectName(u"spb_frlg_tvFrames")
        self.spb_frlg_tvFrames.setGeometry(QRect(10, 110, 121, 25))
        self.spb_frlg_tvFrames.setMaximum(10000000)
        self.lbl_frlg_tvFrames = QLabel(self.tab_FRLG)
        self.lbl_frlg_tvFrames.setObjectName(u"lbl_frlg_tvFrames")
        self.lbl_frlg_tvFrames.setGeometry(QRect(10, 90, 111, 16))
        self.txb_frlg_preReqs = QTextBrowser(self.tab_FRLG)
        self.txb_frlg_preReqs.setObjectName(u"txb_frlg_preReqs")
        self.txb_frlg_preReqs.setGeometry(QRect(140, 60, 261, 201))
        self.txb_frlg_preReqs.setFrameShape(QFrame.Box)
        self.txb_frlg_preReqs.setFrameShadow(QFrame.Plain)
        self.cmb_frlg_deviceSel = QComboBox(self.tab_FRLG)
        self.cmb_frlg_deviceSel.setObjectName(u"cmb_frlg_deviceSel")
        self.cmb_frlg_deviceSel.setGeometry(QRect(180, 270, 51, 24))
        self.lbl_frlg_deviceSel = QLabel(self.tab_FRLG)
        self.lbl_frlg_deviceSel.setObjectName(u"lbl_frlg_deviceSel")
        self.lbl_frlg_deviceSel.setGeometry(QRect(140, 270, 51, 16))
        self.btn_frlg_startSequence = QPushButton(self.tab_FRLG)
        self.btn_frlg_startSequence.setObjectName(u"btn_frlg_startSequence")
        self.btn_frlg_startSequence.setGeometry(QRect(300, 270, 101, 24))
        self.chk_frlg_select = QCheckBox(self.tab_FRLG)
        self.chk_frlg_select.setObjectName(u"chk_frlg_select")
        self.chk_frlg_select.setGeometry(QRect(10, 240, 61, 22))
        self.tab_gameSelection.addTab(self.tab_FRLG, "")
        self.btn_clearDevices = QPushButton(self.centralwidget)
        self.btn_clearDevices.setObjectName(u"btn_clearDevices")
        self.btn_clearDevices.setGeometry(QRect(10, 210, 101, 21))
        self.btn_refreshPorts = QPushButton(self.centralwidget)
        self.btn_refreshPorts.setObjectName(u"btn_refreshPorts")
        self.btn_refreshPorts.setGeometry(QRect(330, 210, 101, 21))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tab_gameSelection.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"NDS Automation", None))
        self.lbl_deviceName.setText(QCoreApplication.translate("MainWindow", u"Device Name", None))
        self.lbl_baudRate.setText(QCoreApplication.translate("MainWindow", u"Baud Rate", None))
        self.lbl_Port.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.btn_addDevice.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.lbl_rseCategory.setText(QCoreApplication.translate("MainWindow", u"Category", None))
        self.lbl_rse_enctounter.setText(QCoreApplication.translate("MainWindow", u"Encounter", None))
        self.btn_rse_startSequence.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.chk_rse_BattleRecord.setText(QCoreApplication.translate("MainWindow", u"Battle Record", None))
        self.chk_rse_painting.setText(QCoreApplication.translate("MainWindow", u"Painting", None))
        self.chk_rse_liveBattery.setText(QCoreApplication.translate("MainWindow", u"Live Battery?", None))
        self.lbl_rse_targetMS.setText(QCoreApplication.translate("MainWindow", u"Target (MS)", None))
        self.lbl_rse_paintingTimer.setText(QCoreApplication.translate("MainWindow", u"Painting Time (MS)", None))
        self.lbl_rse_deviceSel.setText(QCoreApplication.translate("MainWindow", u"Device", None))
        self.tab_gameSelection.setTabText(self.tab_gameSelection.indexOf(self.tab_RSE), QCoreApplication.translate("MainWindow", u"RSE", None))
        self.lbl_frlg_emcounterSel.setText(QCoreApplication.translate("MainWindow", u"Encounter", None))
        self.lbl_frlg_category.setText(QCoreApplication.translate("MainWindow", u"Category", None))
        self.lbl_frlg_button.setText(QCoreApplication.translate("MainWindow", u"Button", None))
        self.lbl_frlg_introTimer.setText(QCoreApplication.translate("MainWindow", u"Intro Timer (MS)", None))
        self.lbl_frlg_totalTime.setText(QCoreApplication.translate("MainWindow", u"Total Time (MS)", None))
        self.spb_frlg_totalTime.setSuffix("")
        self.lbl_frlg_tvFrames.setText(QCoreApplication.translate("MainWindow", u"TV Frames (MS)", None))
        self.lbl_frlg_deviceSel.setText(QCoreApplication.translate("MainWindow", u"Device", None))
        self.btn_frlg_startSequence.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.chk_frlg_select.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.tab_gameSelection.setTabText(self.tab_gameSelection.indexOf(self.tab_FRLG), QCoreApplication.translate("MainWindow", u"FRLG", None))
        self.btn_clearDevices.setText(QCoreApplication.translate("MainWindow", u"Clear Devices", None))
        self.btn_refreshPorts.setText(QCoreApplication.translate("MainWindow", u"Refresh Ports", None))
    # retranslateUi

